name: Новый канал
description: Запрос на добавление нового канала в раздел Другие каналы
title: "[канал]: "
labels: []
assignees:
  - nLight
body:
  - type: input
    id: url
    attributes:
      label: Ссылка на канал
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Название канала
      description: 
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Описание канала со странице О канале
      description: 
      placeholder: 
    validations:
      required: true
